### ISSUE TITLE
p5 - keep track of high scores

### ISSUE THREAD

**Issue by heratyian** [MakeSchool-Tutorials/2048-SpriteBuilder-Swift#10]
func didLoadFromCCB() {
        NSUserDefaults.standardUserDefaults().addObserver(self, forKeyPath: "highscore", options: .allZeros, context: nil)
        updateHighScore()
    }

NSKeyValueObserving options has no value ".allZeros" should use NSKeyValueObservingOptions.Old

func didLoadFromCCB() {
        NSUserDefaults.standardUserDefaults().addObserver(self, forKeyPath: "highscore", options: NSKeyValueObservingOptions.Old, context: nil)
        updateHighScore()
    }

**Comment by dionlarson** [comment]
Fixed in 4f2624b.
