### ISSUE TITLE
Problems in Setting up classes in Xcode

### ISSUE THREAD

**Issue by jeffy-w** [MakeSchool-Tutorials/2048-SpriteBuilder-Swift#11]
1.I just copied the code and Xcode showed some issues about "fun setupBackground":
                        " backgroundTile is immutable"
   then i added  "as! CCNode" to "let backgroundTile = ..." and fixed it.

2.The function didLoadFromCCB need to be added to Grid.Class instead of Grid.swift or there would be an issue "use of unresolved  identifier "setupBackground""
                         func didLoadFromCCB() {
                                       setupBackground()
                                       }

3.Last, I built the project successful, but it stopped running  soon and the output:
2016-01-21 09:34:08.702 My2048Game[885:28936] cocos2d: animation started with frame interval: 60.00
2016-01-21 09:34:08.706 My2048Game[885:28936] cocos2d: surface size: 640x1136
2016-01-21 09:34:08.713 My2048Game[885:28936] CCBReader: Couldn't find member variable: backgroundNode
2016-01-21 09:34:08.713 My2048Game[885:28936] CCBReader: Couldn't find member variable: valueLabel
Could not cast value of type 'CCNode' (0x108cfcf98) to 'My2048Game.Tile' (0x108cfcb30).

**Comment by dionlarson** [comment]
1. I'm not sure why you got an immutable issue with `backgroundTile`. That should not happen if the code is copied correctly.
2. Fixed in 15e1ea7.
3. See page 3 (or P2 on Github). These variables should be part of the `Tile` class:

> Next, open _Tile.swift_ and add the following variables to complete the code connections:
> 
> ```
>   weak var valueLabel: CCLabelTTF!
>   weak var backgroundNode: CCNodeColor!
> ```
