### ISSUE TITLE
On website, tutorial is out of order

### ISSUE THREAD

**Issue by JorrieB** [MakeSchool-Tutorials/2048-SpriteBuilder-Swift#5]
Part 2 is the first one you see, then part 3, then part 1. 

![screen shot 2015-06-18 at 3 07 20 pm](https://cloud.githubusercontent.com/assets/5842238/8243423/c4896d0e-15cb-11e5-961e-ff77f8aa6f24.png)

**Comment by dionlarson** [comment]
Fixed in 1e0313c455aba450cb6d6d4e331a0935fe59c9bc
